PROGRAM::= 'program' 'id' GLOBALS 'main' BLOCK_WITH_DECLARATION 'finish'
GLOBALS::= (DECLARATION | FUNCTION)*
FUNCTION::='function' 'id' '(' TYPE 'id' (',' TYPE 'id')* ')' 'returns' TYPE BLOCK_WITH_DECLARATION
VAR::= TYPE 'id' ('[' [0-9]+ ']')? '=' EXPRESSION
SHAPE::= ('circle' | 'rectangle' | 'triangle') 'id' 'center' '=' POINT 'width' '=' EXPRESSION 'height' '=' EXPRESSION COLOR
BLOCK_WITH_DECLARATION::= '[' (DECLARATION | STATEMENT)* ']'
BLOCK::= '[' STATEMENT* ']'
STATEMENT::= (ASSIGNMENT  | CONDITIONAL | PRINT | LOOP | PAINT | READ | COMMENTS | RETURN)
ASSIGNMENT::= (VAR_ASSIGNMENT | SHAPE_ASSIGNMENT | POINT_ASSIGNMENT | CANVAS_ASSIGNMENT)
VAR_ASSIGNMENT::= 'id' ('[' [0-9]+ ']')? '=' (EXPRESSION | 'id')
SHAPE_ASSIGNMENT::= 'id' '=' 'id' | (('center' '=' POINT) | ('width' '=' EXPRESSION) | ('height' '=' EXPRESSION) | COLOR)+
DECLARATION::= VAR | SHAPE | POINT | CANVAS
POINT::= 'point' 'id' 'x' '=' EXPRESSION 'y' '=' EXPRESSION
POINT_ASSIGNMENT::= 'id' '=' 'id' | (('x' | 'y') '=' EXPRESSION)+
CANVAS::= 'canvas' 'id' 'width' '=' EXPRESSION 'height' '=' EXPRESSION COLOR
CANVAS_ASSIGNMENT::= 'id' ('add' | '=') 'id'  | (('width' '=' EXPRESSION) | ('height' '=' EXPRESSION) | ('color' '=' EXPRESSION))+
EXPRESSION::= EXP ( '>' | '<' | '!=' | '==' | '>=' | '<=') EXP 
EXP::= TERM (('+' | '-') TERM)*
TERM::= FACTOR (('*' | '/') FACTOR)*
FACTOR::= ('(' EXPRESSION ')') | ('+' | '-')* 'id' ('[' [0-9]+ ']')?
CONDITIONAL::= 'if' '(' EXPRESSION ')' BLOCK ('elsif' '(' EXPRESSION ')' BLOCK)* ('else' BLOCK)?
PRINT::= 'print' '(' (EXPRESSION | 'id') (',' (EXPRESSION | 'id') )* ')' 
READ::= 'read' 'id'
PAINT::= 'paint' 'id'
RETURN::= 'return' EXPRESSION
FOR_LOOP::= 'for' 'each' 'id' 'in' RANGE ('by' ('integer' | 'decimal'))? BLOCK
WHILE_LOOP::= 'while' '(' EXPRESSION ')' BLOCK
COLOR::= 'color' 'id' 'red' '=' EXPRESSION 'green' '=' EXPRESSION 'blue' '=' EXPRESSION
